dataset:
  target: dataset.codeformer.CodeformerDataset_Mask
  params:
    # Path to the file list.
    #file_list: /home/user001/zwl/data/FFHQ512/train.list
    file_list: /home/user001/zwl/zyx/Diffbir/10955/meta/inp.list
    # wider :34.391226832176  lfw:38.66
    out_size: 512
    crop_type: none
    use_hflip: False
    
    blur_kernel_size: 41
    kernel_list: ['iso', 'aniso']
    kernel_prob: [0.5, 0.5]
    blur_sigma: [0.1, 10]
    downsample_range: [0.8, 8]
    noise_range: [0, 20]
    jpeg_range: [60, 100]

data_loader:
  batch_size: 4
  shuffle: false
  num_workers: 16
  drop_last: true

batch_transform:
  target: dataset.batch_transform.IdentityBatchTransform
