dataset:
  target: dataset.codeformer.CodeformerDataset
  params:
    # Path to the file list.
    file_list: /home/user001/zwl/data/FFHQ512/val.list
    #file_list: /data1/zyx/celeba_512_validation_list_files/val_lq.list
    
    out_size: 512
    crop_type: none
    use_hflip: False
    
    blur_kernel_size: 41
    kernel_list: ['iso', 'aniso']
    kernel_prob: [0.5, 0.5]
    blur_sigma: [0.1, 10]
    downsample_range: [0.8, 8]
    noise_range: [0, 20]
    jpeg_range: [60, 100]

    # color_jitter_prob: 0.3
    # color_jitter_shift: 20
    # color_jitter_pt_prob: 0.3
    # gray_prob: 0.01


data_loader:
  batch_size: 3
  shuffle: false
  num_workers: 16
  drop_last: true

batch_transform:
  target: dataset.batch_transform.IdentityBatchTransform
