dataset:
  target: dataset.codeformer.CodeformerDatasetLQ
  params:
    # Path to the file list.
    hq_list: /home/user001/zwl/zyx/Diffbir/ocr_list/val_hq.list
    lq_list: /home/user001/zwl/zyx/Diffbir/ocr_list/val_lq.list
    out_size: 512
    crop_type: center
    use_hflip: True
    
    blur_kernel_size: 41
    kernel_list: ['iso', 'aniso']
    kernel_prob: [0.5, 0.5]
    blur_sigma: [0.1, 12]
    downsample_range: [1, 12]
    noise_range: [0, 15]
    jpeg_range: [30, 100]

data_loader:
  batch_size: 2
  shuffle: false
  num_workers: 16
  drop_last: true

batch_transform:
  target: dataset.batch_transform.IdentityBatchTransform
