data:
  target: dataset.data_module.BIRDataModule
  params:
    # Path to training set configuration file.
    train_config: /home/user001/zwl/zyx/Diffbir/configs/dataset/face_train.yaml
    # Path to validation set configuration file.
    val_config: /home/user001/zwl/zyx/Diffbir/configs/dataset/face_val.yaml

model:
  # You can set learning rate in the following configuration file.
  config: configs/model/cldm.yaml
  # Path to the checkpoints or weights you want to resume. At the begining, 
  # this should be set to the initial weights created by scripts/make_stage2_init_weight.py.
  # resume: /home/user001/zwl/data/flowir_work_dirs/gray3/lightning_logs/version_0/checkpoints/step=9999.ckpt
  # resume: /home/user001/zwl/data/flowir_work_dirs/enhance2/lightning_logs/version_0/checkpoints/step=4999.ckpt
  # resume: /home/zyx/DiffBIR-main/work_dirs/exp4/lightning_logs/version_18/checkpoints/step=24999.ckpt
  resume: /home/user001/zwl/data/cldm_weights/face_full_v1.ckpt

lightning:
  seed: 231
  
  trainer:
    accelerator: ddp
    precision: 32
    # Indices of GPUs used for training.
    gpus: [1,2,3,4,5,6,7]
    # Path to save logs and checkpoints.
    default_root_dir: /home/user001/zwl/data/flowir_work_dirs/lock_sd
    # Max number of training steps (batches).
    max_steps: 250001
    # Validation frequency in terms of training steps.
    val_check_interval: 500
    log_every_n_steps: 50
    # Accumulate gradients from multiple batches so as to increase batch size.
    accumulate_grad_batches: 1
  
  callbacks:
    - target: model.callbacks.ImageLogger
      params:
        # Log frequency of image logger.
        log_every_n_steps: 250
        max_images_each_step: 4
        log_images_kwargs: ~

    - target: model.callbacks.ModelCheckpoint
      params:
        # Frequency of saving checkpoints.
        every_n_train_steps: 3000
        save_top_k: -1
        filename: "{step}"
